from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, ForeignKey, Numeric, Date, func
from sqlalchemy.orm import relationship
from typing import TYPE_CHECKING, Optional
from . import Base

if TYPE_CHECKING:
    from .user import User
    from .quiz import QuizAttempt
    from .course_content import CourseContent


class AdaptiveLearningPath(Base):
    """
    Stores personalized learning paths generated by LLM analysis of user progress
    """
    __tablename__ = "adaptive_learning_paths"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    generated_at = Column(DateTime, nullable=False, default=func.now())
    recommended_courses = Column(Text, nullable=False)  # JSON string of recommended courses
    reasoning = Column(Text, nullable=True)  # Explanation of why these recommendations were made
    valid_until = Column(DateTime, nullable=True)  # Expiration date for the recommendations
    is_active = Column(Boolean, default=True, nullable=False)
    cost_usd = Column(Numeric(precision=10, scale=2), nullable=True)  # Cost incurred to generate this path

    # Relationships
    user = relationship("User", back_populates="adaptive_learning_paths")

    __table_args__ = (
        # Index on user_id and is_active for quick retrieval of active paths
        # Index on generated_at for time-based queries
    )


class LLMGradeAssessment(Base):
    """
    Stores LLM-graded assessments for free-form responses
    """
    __tablename__ = "llm_grade_assessments"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    quiz_attempt_id = Column(Integer, ForeignKey("quiz_attempts.id"), nullable=False)
    question_id = Column(String, nullable=False)  # Could be UUID or string depending on how questions are stored
    original_response = Column(Text, nullable=False)  # The user's original free-form response
    llm_grade = Column(Text, nullable=False)  # JSON string of detailed grading from the LLM
    graded_at = Column(DateTime, nullable=False, default=func.now())
    cost_usd = Column(Numeric(precision=10, scale=2), nullable=True)  # Cost incurred to perform the LLM grading
    is_valid = Column(Boolean, default=True, nullable=False)

    # Relationships
    user = relationship("User", back_populates="llm_grade_assessments")
    quiz_attempt = relationship("QuizAttempt", back_populates="llm_grade_assessments")

    __table_args__ = (
        # Index on user_id and quiz_attempt_id for quick lookup
        # Index on question_id for analytics
    )


class HybridFeatureUsage(Base):
    """
    Tracks usage of hybrid intelligence features for cost accounting and access control
    """
    __tablename__ = "hybrid_feature_usage"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    feature_type = Column(String(50), nullable=False)  # Type of hybrid feature used (adaptive_path, llm_grading)
    usage_timestamp = Column(DateTime, nullable=False, default=func.now())
    request_details = Column(Text, nullable=True)  # JSON string of details about the request made
    response_summary = Column(Text, nullable=True)  # JSON string of summary of the response received
    cost_usd = Column(Numeric(precision=10, scale=2), nullable=False)  # Cost incurred for this usage
    tokens_used = Column(Integer, nullable=True)  # Number of tokens consumed (input + output)

    # Relationships
    user = relationship("User", back_populates="hybrid_feature_usage")

    __table_args__ = (
        # Index on user_id and usage_timestamp for user activity tracking
        # Index on feature_type for feature usage analytics
        # Index on usage_timestamp for time-based queries
    )


class CostMetric(Base):
    """
    Aggregated cost metrics for billing and analytics
    """
    __tablename__ = "cost_metrics"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    metric_period_start = Column(Date, nullable=False)
    metric_period_end = Column(Date, nullable=False)
    total_cost_usd = Column(Numeric(precision=10, scale=2), nullable=False)
    total_tokens = Column(Integer, nullable=False)
    feature_breakdown = Column(Text, nullable=False)  # JSON string of cost breakdown by feature type
    calculated_at = Column(DateTime, nullable=False, default=func.now())

    # Relationships
    user = relationship("User", back_populates="cost_metrics")

    __table_args__ = (
        # Index on user_id and metric_period_start for user billing
        # Index on metric_period_start for period-based queries
    )